name              'osl-mattermost'
maintainer        'Oregon State University'
maintainer_email  'chef@osuosl.org'
license           'All Rights Reserved'
description       'Installs/Configures osl-mattermost'
issues_url        'https://github.com/osuosl-cookbooks/osl-mattermost/issues'
source_url        'https://github.com/osuosl-cookbooks/osl-mattermost'
chef_version      '>= 16.0'
version           '0.1.0'

supports          'centos', '~> 7.0'
supports          'centos_stream', '~> 8.0'
