name              'osl-mattermost'
maintainer        'Oregon State University'
maintainer_email  'chef@osuosl.org'
license           'All Rights Reserved'
description       'Installs/Configures osl-mattermost'
issues_url        'https://github.com/osuosl-cookbooks/osl-mattermost/issues'
source_url        'https://github.com/osuosl-cookbooks/osl-mattermost'
chef_version      '>= 17.0'
version           '1.1.2'

depends           'ark'
depends           'osl-acme'
depends           'osl-docker'
depends           'osl-git'
depends           'osl-nginx'

supports          'almalinux', '~> 8.0'
